copyright: "Kx Systems 1995-2016"
dev_addr: '0.0.0.0:8000'
docs_dir: 'docs'
extra_css: [stylesheets/extra.css]
extra_javascript: [scripts/fdtracker.js,scripts/googleanalytics.js]
# google_analytics: ['UA-3462586-1','kx.com', 'code.kx.com']
site_dir: 'site'
site_author: 'Kx Systems'
site_description: Resources for kdb+ programmers
site_favicon: 'img/favicon.ico'
# config.site_name: 'code.kx.com'
site_name: 'code.kx.com'
site_url: 'http://code.kx.com'
remote_branch: 'master'
# repo_name: 'GitHub'
# repo_url: 'https://github.com/kxsystems/docs'
theme: 'material'
# theme_dir for favicon
#theme_dir: 'theme'
extra:
  logo: 'img/Kx_Logo_blue.png'
  palette: 
    primary: 'blue'
    accent: 'deep orange'
  # version: '0.1.0'
pages:
  - Home: index.md
  - Get started: learn.md
  - Q for Mortals: qformortals3.md
  - Reference: reference.md
  - Developer: developer.md
  - Library: library.md